name: Build API

# Controls when the action will run. 
on:
  workflow_call: 
    
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with: 
          node-version: 16.x

      - name: Install node modules & build
        run: |
          npm ci --workspace @strawberrylemonade/core
          npm run build
        working-directory: packages/api

      - uses: montudor/action-zip@v1
        name: Install ZIP

      - name: Copy node modules
        run: cp -r -a ../../node_modules dist/node_modules
        working-directory: packages/api

      - name: Zip build directory
        run: zip -r build.zip .
        working-directory: packages/api/dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: packages/api/dist/build.zip
