name: Build and deploy UI

on:
  push:
      branches: [ main ]
      paths:
      - 'packages/ui/**'

  workflow_dispatch:
  
jobs:
  development: 
    name: Deploy to development
    uses: goodhub/goodhub/.github/workflows/deploy-ui.yaml@main
    with:
      url: beta.goodhub.org.uk
      environment: Development
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_PROJECT_EXTERNAL_ID: ${{ secrets.VERCEL_PROJECT_EXTERNAL_ID }}
    
  production:
    name: Deploy to production
    needs: [development]
    uses: goodhub/goodhub/.github/workflows/deploy-io.yaml@main
    with:
      url: app.goodhub.org.uk
      environment: Production
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_PROJECT_EXTERNAL_ID: ${{ secrets.VERCEL_PROJECT_EXTERNAL_ID }}
