name: Build and deploy UI

on:
  push:
      branches: [ main ]
      paths:
      - 'packages/functions/**'
      - 'packages/infrastructure/**'

  workflow_dispatch:
  
jobs:
  development: 
    name: Deploy to development
    uses: goodhub/goodhub/.github/workflows/deploy-functions.yaml@main
    with:
      stack: dev
      environment: Development
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    
  production:
    name: Deploy to production
    needs: [development]
    uses: goodhub/goodhub/.github/workflows/deploy-functions.yaml@main
    with:
      stack: dev
      environment: Development
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
