name: Build and deploy API

on:
  push:
      branches: [ main ]
      paths:
      - 'packages/api/**'

  workflow_dispatch:
  
jobs:
  build:
    name: Build
    uses: goodhub/goodhub/.github/workflows/build-api.yaml@main

  development: 
    name: Deploy to development
    needs: build
    uses: goodhub/goodhub/.github/workflows/deploy-api.yaml@main
    with:
      stack: dev
      environment: Development
    
  production:
    name: Deploy to production
    needs: build
    uses: goodhub/goodhub/.github/workflows/deploy-api.yaml@main
    with:
      stack: prod
      environment: Production
