name: Deploy API

# Controls when the action will run. 
on:
  workflow_call:
    inputs:
      stack:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      PULUMI_ACCESS_TOKEN:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  development:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: npm install
      
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ inputs.stack }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
