name: Deploy UI
on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true
      VERCEL_PROJECT_EXTERNAL_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}

    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        name: Build & deploy main site
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} 
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: --prod
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: |
            ${{ inputs.url }} 
          working-directory: packages/ui

      - uses: amondnet/vercel-action@v20
        name: Build & deploy external site
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} 
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_EXTERNAL_ID }}
          vercel-args: --prod
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: |
            external.${{ inputs.url }} 
          working-directory: packages/ui
