name: Deploy UI
on:
  push:
      branches: [ main ]
      paths:
      - 'packages/ui/**'
      
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: https://beta.goodhub.org.uk

    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} 
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: --prod
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: |
            beta.goodhub.org.uk
          working-directory: packages/ui

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} 
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_EXTERNAL_ID }}
          vercel-args: --prod
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: |
            external.beta.goodhub.org.uk
          working-directory: packages/ui
