name: Trigger core API build & deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
    - 'packages/api/**'
    - 'packages/shared/**'
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: job
          custom_payload: |
            {
              text: `A new API ${process.env.AS_JOB} has started for "goodhub-development-core".`,
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - uses: actions/checkout@main
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with: 
          node-version: '14.x'

      - name: Install node modules & build
        run: |
          npm install
          npm run build
          cp -r node_modules dist/node_modules
        working-directory: packages/api
        
      - uses: papeloto/action-zip@v1
        name: Zip build directory
        with:
          files: packages/api/dist
          dest: build.zip
        
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: goodhub-development-core
          publish-profile: ${{ secrets.DEVELOPMENT_CORE_PUBLISH_PROFILE }}
          package: build.zip

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: job
          custom_payload: |
            {
              text: `${'${{ job.status }}' === 'success' ? 'Successful' : '${{ job.status }}' === 'failure' ? 'Failed' : 'Unknown status of'} build & deploy for "goodhub-development-core"`,
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
