name: Trigger core API build & deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
    - 'server/content-core/**'
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Install node modules & build
        run: |
          npm install
          npm run build
          zip -r build.zip dist
        working-directory: server/content-core
        
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: goodhub-development-core
          publish-profile: ${{ secrets.DEVELOPMENT_CORE_PUBLISH_PROFILE }}
          package: server/content-core/build.zip
