name: Trigger core API build & deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
    - 'server/content-core/**'
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with: 
          node-version: '14.x'
          
      - name: Add token to .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${AUTH_TOKEN}" >> .npmrc
        env:  
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install node modules & build
        run: |
          npm install
          npm run build
          cp -r node_modules dist/node_modules
        working-directory: server/content-core
        
      - uses: papeloto/action-zip@v1
        name: Zip build directory
        with:
          files: server/content-core/dist
          dest: build.zip
        
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: goodhub-development-core
          publish-profile: ${{ secrets.DEVELOPMENT_CORE_PUBLISH_PROFILE }}
          package: build.zip
